template: |
  <|begin_of_text|><|start_header_id|>system<|end_header_id|>
  You are a helpful AI assistant.
  <|eot_id|>
  <|start_header_id|>user<|end_header_id|>
  {user_prompt}
  <|eot_id|>
  <|start_header_id|>assistant<|end_header_id|>

template_stop: "<|eot_id|>"

stop_sequences:
  - "<|eot_id|>"
  - "<|start_header_id|>user<|end_header_id|>"
  - "<|start_header_id|>system<|end_header_id|>"